import {Component, computed, inject, signal} from '@angular/core';
import {FormBuilder, FormControl, ReactiveFormsModule, Validators} from '@angular/forms';
import {TranslateModule} from '@ngx-translate/core';
import {CommonModule} from '@angular/common';
import {TrackingStore} from '@tracking/application/tracking-store';
import {Vehicle} from '@tracking/domain/model/vehicle.entity';
import {IamStore} from '@iam/application/iam-store';

@Component({
  selector: 'app-manage-vehicles',
  imports: [ReactiveFormsModule, TranslateModule, CommonModule],
  templateUrl: './manage-vehicles.html',
  styleUrl: './manage-vehicles.css'
})
export class ManageVehicles {
  private fb = inject(FormBuilder);
  private trackingStore = inject(TrackingStore);
  private iamStore = inject(IamStore);

  sessionUser = this.iamStore.sessionUser;

  // Signals
  showModal = signal(false);
  isEditMode = signal(false);
  selectedVehicleId = signal<string | null>(null);
  vehiclesByUserId = computed(() => {
    const userId = this.sessionUser()?.id;
    return this.trackingStore.vehicles().filter(vehicle => vehicle.id_user === userId);
  })

  // Form
  vehicleForm = this.fb.group({
    model: new FormControl<string>('', { nonNullable: true, validators: [Validators.required, Validators.minLength(2)] }),
    brand: new FormControl<string>('', { nonNullable: true, validators: [Validators.required, Validators.minLength(2)] }),
    plate: new FormControl<string>('', { nonNullable: true, validators: [Validators.required, Validators.minLength(3)] }),
    color: new FormControl<string>('', { nonNullable: true, validators: [Validators.required, Validators.minLength(2)] }),
    type: new FormControl<string>('', { nonNullable: true, validators: [Validators.required, Validators.minLength(2)] }),
  });

  // Methods
  onAddVehicle(): void {
    this.isEditMode.set(false);
    this.selectedVehicleId.set(null);
    this.vehicleForm.reset();
    this.showModal.set(true);
  }

  onEditVehicle(vehicle: Vehicle): void {
    this.isEditMode.set(true);
    this.selectedVehicleId.set(vehicle.id);
    this.vehicleForm.patchValue({
      model: vehicle.model,
      brand: vehicle.vehicle_brand,
      type: vehicle.vehicle_type,
      plate: vehicle.vehicle_plate,
      color: vehicle.color
    });
    this.showModal.set(true);
  }

  onDeleteVehicle(vehicleId: string): void {
    if (confirm('¿Está seguro de eliminar este vehículo?')) {
      this.trackingStore.deleteVehicle(vehicleId);
    }
  }

  onCloseModal(): void {
    this.showModal.set(false);
    this.vehicleForm.reset();
    this.selectedVehicleId.set(null);
  }

  onSubmit(): void {
    if (this.vehicleForm.invalid) {
      this.vehicleForm.markAllAsTouched();
      return;
    }

    const formData = this.vehicleForm.getRawValue();
    const userId = this.sessionUser()?.id || '';

    if (this.isEditMode()) {
      // Update existing vehicle
      const vehicleId = this.selectedVehicleId();
      if (vehicleId) {
        const updatedVehicle = new Vehicle({
          id_vehicle: vehicleId,
          model: formData.model,
          vehicle_plate: formData.plate,
          color: formData.color,
          id_user: userId,
          vehicle_brand: formData.brand,
          vehicle_type: formData.type,
          state_maintenance: 0
        });
        this.trackingStore.updateVehicle(updatedVehicle);
      }
    } else {
      // Create new vehicle
      const newVehicle = new Vehicle({
        id_vehicle: '', // Will be generated by backend
        model: formData.model,
        vehicle_plate: formData.plate,
        color: formData.color,
        id_user: userId,
        vehicle_brand: formData.brand,
        vehicle_type: formData.type,
        state_maintenance: 0
      });
      this.trackingStore.addVehicle(newVehicle);
    }

    this.onCloseModal();
  }
}
